title: Ian Mobbs
author: Ian Mobbs
encoding: utf-8

permalink: /projects/:title
url: "http://ianmobbs.com"
baseurl: ""

sass:
    style: compressed
    sass_dir: _sass

markdown: kramdown
highlighter: rouge