title: Ian Mobbs
author: Ian Mobbs
encoding: utf-8

permalink: /projects/:title
url: "https://ianmobbs.com"
baseurl: ""

sass:
    style: compressed
    sass_dir: _sass

markdown: kramdown
highlighter: rouge
# for line numbers:
# kramdown:
#     syntax_highlighter: rouge
#     syntax_highlighter_opts:
#         block:
#             line_numbers: true
